[Rule]
# Put these personal rules before broad public rules.
RULE-SET,https://raw.githubusercontent.com/aimcrfui/surge-rules/main/rules/reject.list,REJECT
RULE-SET,https://raw.githubusercontent.com/aimcrfui/surge-rules/main/rules/direct.list,DIRECT
RULE-SET,https://raw.githubusercontent.com/aimcrfui/surge-rules/main/rules/ai.list,AIGC
RULE-SET,https://raw.githubusercontent.com/aimcrfui/surge-rules/main/rules/stream.list,Stream
RULE-SET,https://raw.githubusercontent.com/aimcrfui/surge-rules/main/rules/proxy.list,Foreign
