#!/usr/bin/env python3
"""Generate personal Surge rule sets from configured upstream providers."""

from __future__ import annotations

import hashlib
import json
import sys
import urllib.error
import urllib.request
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PROVIDERS_PATH = ROOT / "sources" / "providers.json"
PERSONAL_DIR = ROOT / "personal"
RULES_DIR = ROOT / "rules"

SUPPORTED_RULE_TYPES = {
    "DOMAIN",
    "DOMAIN-SUFFIX",
    "DOMAIN-KEYWORD",
    "DOMAIN-WILDCARD",
    "IP-CIDR",
    "IP-CIDR6",
    "URL-REGEX",
    "USER-AGENT",
}

SURGE_POLICIES = {
    "DIRECT",
    "REJECT",
    "REJECT-TINYGIF",
    "PROXY",
    "Proxy",
    "Foreign",
    "AIGC",
    "Stream",
    "Home",
    "Telegram",
}


def fetch_text(url: str) -> str:
    request = urllib.request.Request(
        url,
        headers={"User-Agent": "aimcrfui-surge-rules/1.0"},
    )
    try:
        with urllib.request.urlopen(request, timeout=30) as response:
            charset = response.headers.get_content_charset() or "utf-8"
            return response.read().decode(charset, errors="replace")
    except (urllib.error.URLError, TimeoutError) as exc:
        raise RuntimeError(f"failed to fetch {url}: {exc}") from exc


def normalize_rule(line: str) -> str | None:
    value = line.strip()
    if not value or value.startswith("#") or value.startswith("//"):
        return None

    if value.startswith("RULE-SET,") or value.startswith("DOMAIN-SET,"):
        return None

    parts = [part.strip() for part in value.split(",")]
    if len(parts) < 2 or parts[0] not in SUPPORTED_RULE_TYPES:
        return None

    if "7h1s_rul35et_i5_mad3_by_5ukk4w" in value:
        return None

    if len(parts) >= 3 and parts[-1] in SURGE_POLICIES:
        parts = parts[:-1]
    elif len(parts) >= 4 and parts[-2] in SURGE_POLICIES:
        parts = parts[:-2] + parts[-1:]

    return ",".join(parts)


def load_personal_rules(category: str) -> list[str]:
    path = PERSONAL_DIR / f"{category}.list"
    if not path.exists():
        return []
    rules: list[str] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        rule = normalize_rule(line)
        if rule:
            rules.append(rule)
    return rules


def write_category(category: str, providers: list[dict[str, str]]) -> dict[str, object]:
    seen: set[str] = set()
    rules: list[str] = []
    source_meta: list[dict[str, object]] = []

    for provider in providers:
        text = fetch_text(provider["url"])
        normalized = []
        for line in text.splitlines():
            rule = normalize_rule(line)
            if rule and rule not in seen:
                seen.add(rule)
                normalized.append(rule)
                rules.append(rule)

        source_meta.append(
            {
                "name": provider["name"],
                "url": provider["url"],
                "rule_count": len(normalized),
                "sha256": hashlib.sha256(text.encode("utf-8")).hexdigest(),
            }
        )

    personal_rules = []
    for rule in load_personal_rules(category):
        if rule not in seen:
            seen.add(rule)
            personal_rules.append(rule)
            rules.append(rule)

    RULES_DIR.mkdir(parents=True, exist_ok=True)
    target = RULES_DIR / f"{category}.list"
    header = [
        f"# {category}.list",
        "# Generated by scripts/update_rules.py. Do not edit this file directly.",
        "# Add personal entries in personal/%s.list." % category,
        "# Sources:",
    ]
    for meta in source_meta:
        header.append("# - {name}: {url}".format(**meta))
    if personal_rules:
        header.append("# - personal/%s.list" % category)

    target.write_text("\n".join(header + [""] + rules) + "\n", encoding="utf-8")

    return {
        "category": category,
        "output": str(target.relative_to(ROOT)),
        "rule_count": len(rules),
        "personal_rule_count": len(personal_rules),
        "sources": source_meta,
    }


def main() -> int:
    config = json.loads(PROVIDERS_PATH.read_text(encoding="utf-8"))
    categories = config.get("categories", {})
    metadata = {
        "schema": 1,
        "source": str(PROVIDERS_PATH.relative_to(ROOT)),
        "categories": [],
    }

    for category, providers in categories.items():
        metadata["categories"].append(write_category(category, providers))

    (RULES_DIR / "metadata.json").write_text(
        json.dumps(metadata, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
